# Generated by Django 6.0.5 on 2026-05-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('agent', 'agent'), ('admin', 'admin')], default='user', max_length=10),
        ),
    ]
