# Generated by Django 6.0.5 on 2026-06-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
