# Generated by Django 6.0.5 on 2026-05-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('pending', 'در انتظار'), ('closed', 'بسته'), ('revision', 'نیاز به اصلاح')], default='open', max_length=10),
        ),
    ]
