# Generated by Django 6.0.5 on 2026-05-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
